name = "olive"
uuid = "c1a59971-6f4d-46be-b520-66df1589e441"
authors = ["emmac "]
version = "0.1.0"

[deps]
Gattino = "f0fb3ee5-f608-41f3-a42d-dac276373afc"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Olive = "724ecaf6-c7a0-4c22-b37e-0bb7b4193da8"

[groups.root]
cells = ["code", "markdown"]
dirs = ["home"]
load = ["olivebase"]
uris = ["./olive"]

[groups.guest]
cells = ["code", "markdown"]
dirs = ["home"]
load = ["olivebase"]
uris = ["./olive"]

[olive]
home = "./olive"
root = "emmac"
defaultgroup = "all"

[compat]
Gattino = "0.1.1"
Pkg = "1.11.0"
Olive = "0.0.93"

[oliveusers.guest]
group = "guest"

    [oliveusers.guest.highlighting.julia]
    string = "#4e944d"
    global = "#ff0066"
    number = "#8b0000"
    using = "#006C67"
    func = "#944d94"
    for = "#944d94"
    struct = "#944d94"
    funcn = "#2d65a8"
    mutable = "#a82d38"
    in = "#006C67"
    import = "#fc038c"
    op = "#0C023E"
    comment = "#808080"
    default = "#3D3D3D"
    macro = "#43B3AE"
    if = "#944d94"
    module = "#b81870"
    params = "#00008B"
    end = "#b81870"
    begin = "#a82d38"
    exit = "#cc0099"
    interp = "#420000"
    char = "#8b0000"
    abstract = "#a82d38"
    type = "#D67229"

    [oliveusers.guest.highlighting.toml]
    string = "#4e944d"
    number = "#8b0000"
    default = "#2d65a8"
    keys = "#D67229"
    equals = "#1f0c2e"

    [oliveusers.guest.highlighting.markdown]
    bold = "#0f1e73"
    italic = "#8b0000"
    default = "#1c0906"
    keys = "#ffc000"
    link = "#8b0000"
    code = "#8b0000"
    heading = "#1f0c2e"

    [oliveusers.guest.creatorkeys]
    v = "markdown"
    c = "code"
    m = "module"
    "/" = "helprepl"
    ";" = "shellrepl"
    "]" = "pkgrepl"
    i = "include"

    [oliveusers.guest.keybindings]
    delete = ["Delete", "ctrl", "shift"]
    explorer = ["E", "ctrl"]
    find = ["F", "ctrl"]
    undo = ["Z", "ctrl", "shift"]
    cut = ["X", "ctrl", "shift"]
    evaluate = ["Enter", "shift"]
    copy = ["C", "ctrl", "shift"]
    saveas = ["S", "ctrl", "shift"]
    focusdown = ["ArrowDown", "shift"]
    up = ["ArrowUp", "ctrl", "shift"]
    select = ["A", "ctrl", "shift"]
    save = ["s", "ctrl"]
    focusup = ["ArrowUp", "shift"]
    down = ["ArrowDown", "ctrl", "shift"]
    new = ["Enter", "ctrl", "shift"]
    paste = ["V", "ctrl", "shift"]
    open = ["O", "ctrl"]
    project-new = ["N", "ctrl", "shift"]

[oliveusers.emmac]
recents = ["./olive/src/olive.jl", "./olive/home/users/emmac/profile/profile.jl"]
group = "root"

    [oliveusers.emmac.creatorkeys]
    v = "markdown"
    c = "code"
    m = "module"
    "/" = "helprepl"
    ";" = "shellrepl"
    "]" = "pkgrepl"
    i = "include"

    [oliveusers.emmac.highlighting.julia]
    string = "#007958"
    number = "#8b0000"
    using = "#006C67"
    func = "#fc038c"
    for = "#fc038c"
    struct = "#fc038c"
    funcn = "#2F387B"
    mutable = "#006C67"
    in = "#006C67"
    import = "#fc038c"
    op = "#0C023E"
    comment = "#808080"
    default = "#3D3D3D"
    if = "#fc038c"
    module = "#b81870"
    end = "#b81870"
    begin = "#fc038c"
    exit = "#cc0099"
    interp = "#420000"
    char = "#8b0000"
    abstract = "#006C67"
    type = "#D67229"

    [oliveusers.emmac.highlighting.toml]
    string = "#007958"
    number = "#8b0000"
    default = "darkblue"
    keys = "#D67229"
    equals = "purple"

    [oliveusers.emmac.highlighting.markdown]
    bold = "darkblue"
    point = "darkgreen"
    italic = "#8b0000"
    default = "brown"
    keys = "#ffc000"
    link = "#8b0000"
    code = "#8b0000"
    heading = "purple"

    [oliveusers.emmac.keybindings]
    delete = ["Delete", "ctrl", "shift"]
    explorer = ["E", "ctrl"]
    find = ["F", "ctrl"]
    cut = ["X", "ctrl", "shift"]
    copy = ["C", "ctrl", "shift"]
    evaluate = ["Enter", "shift"]
    saveas = ["S", "ctrl", "shift"]
    focusdown = ["ArrowDown", "shift"]
    up = ["ArrowUp", "ctrl", "shift"]
    save = ["s", "ctrl"]
    focusup = ["ArrowUp", "shift"]
    down = ["ArrowDown", "ctrl", "shift"]
    new = ["Enter", "ctrl", "shift"]
    paste = ["V", "ctrl", "shift"]
    open = ["O", "ctrl"]
