home = "./olive"
root = "emmac"
wd = "/home/emmac/dev/packages/olive/OliveCreator.jl"
name = "olive"
defaultgroup = "all"
version = "0.1.0"
uuid = "c1a59971-6f4d-46be-b520-66df1589e441"
authors = ["emmac "]

[groups.root]
cells = ["code", "markdown"]
dirs = ["home"]
uris = ["./olive"]
load = ["olivebase"]

[groups.users]
cells = ["code", "markdown"]
dirs = []
uris = []
load = ["olivebase"]

[groups.guest]
cells = ["code", "markdown"]
dirs = []
uris = []
load = ["olivebase"]

[olive]
home = "./olive"
root = "emmac"
defaultgroup = "all"

[compat]
Gattino = "0.1.1"
Pkg = "1.11.0"
Olive = "0.0.93"

[oliveusers.guest]
group = "guest"

    [oliveusers.guest.highlighting.julia]
    string = "#4e944d"
    global = "#ff0066"
    number = "#8b0000"
    using = "#006C67"
    func = "#944d94"
    for = "#944d94"
    struct = "#944d94"
    funcn = "#2d65a8"
    mutable = "#a82d38"
    in = "#006C67"
    import = "#fc038c"
    op = "#0C023E"
    comment = "#808080"
    default = "#3D3D3D"
    macro = "#43B3AE"
    if = "#944d94"
    module = "#b81870"
    params = "#00008B"
    end = "#b81870"
    begin = "#a82d38"
    exit = "#cc0099"
    interp = "#420000"
    char = "#8b0000"
    abstract = "#a82d38"
    type = "#D67229"

    [oliveusers.guest.highlighting.toml]
    string = "#4e944d"
    number = "#8b0000"
    default = "#2d65a8"
    keys = "#D67229"
    equals = "#1f0c2e"

    [oliveusers.guest.highlighting.markdown]
    bold = "#0f1e73"
    italic = "#8b0000"
    default = "#1c0906"
    keys = "#ffc000"
    link = "#8b0000"
    code = "#8b0000"
    heading = "#1f0c2e"

    [oliveusers.guest.creatorkeys]
    v = "markdown"
    c = "code"
    m = "module"
    "/" = "helprepl"
    ";" = "shellrepl"
    "]" = "pkgrepl"
    i = "include"

    [oliveusers.guest.keybindings]
    delete = ["Delete", "ctrl", "shift"]
    explorer = ["E", "ctrl"]
    find = ["F", "ctrl"]
    undo = ["Z", "ctrl", "shift"]
    cut = ["X", "ctrl", "shift"]
    copy = ["C", "ctrl", "shift"]
    evaluate = ["Enter", "shift"]
    saveas = ["S", "ctrl", "shift"]
    focusdown = ["ArrowDown", "shift"]
    up = ["ArrowUp", "ctrl", "shift"]
    select = ["A", "ctrl", "shift"]
    save = ["s", "ctrl"]
    focusup = ["ArrowUp", "shift"]
    down = ["ArrowDown", "ctrl", "shift"]
    new = ["Enter", "ctrl", "shift"]
    paste = ["V", "ctrl", "shift"]
    open = ["O", "ctrl"]
    project-new = ["N", "ctrl", "shift"]

[oliveusers.emmac]
messages = ["global", "hello world"]
recents = ["./olive/src/olive.jl", "./olive/home/users/emmac/profile/profile.jl", "/home/emmac/dev/packages/olive/OliveCreator.jl/dev.jl"]
img = ""
achievements = []
group = "root"

    [oliveusers.emmac.missions]
    0 = false

    [oliveusers.emmac.creatorkeys]
    v = "markdown"
    c = "code"
    m = "module"
    "/" = "helprepl"
    ";" = "shellrepl"
    "]" = "pkgrepl"
    i = "include"

    [oliveusers.emmac.highlighting.julia]
    string = "#44fd8b"
    number = "#ff4747"
    using = "#42d7cf"
    func = "#ff61b8"
    for = "#e7ffa3"
    struct = "#fc038c"
    funcn = "#c7cdff"
    mutable = "#006C67"
    in = "#64f7ef"
    import = "#ff8fcd"
    op = "#dca6dd"
    comment = "#e9ead1"
    default = "#ffffff"
    if = "#ff61b8"
    module = "#ffa3b6"
    end = "#ae57d6"
    begin = "#fc038c"
    exit = "#cc0099"
    interp = "#ccf7ff"
    char = "#bd5dd0"
    abstract = "#6cd5d0"
    type = "#ffaf75"

    [oliveusers.emmac.highlighting.toml]
    string = "#29f5be"
    number = "#f05656"
    default = "#ffffff"
    keys = "#D67229"
    equals = "#d477d1"

    [oliveusers.emmac.highlighting.markdown]
    bold = "#da8349"
    point = "#df7cdc"
    italic = "#5cdb6b"
    default = "#ffead6"
    keys = "#ffc000"
    link = "#8cadd9"
    code = "#dd6464"
    heading = "#adb3ff"

    [oliveusers.emmac.keybindings]
    delete = ["Delete", "ctrl", "shift"]
    explorer = ["E", "ctrl"]
    find = ["F", "ctrl"]
    undo = ["Z", "ctrl", "shift"]
    cut = ["X", "ctrl", "shift"]
    evaluate = ["Enter", "shift"]
    copy = ["C", "ctrl", "shift"]
    saveas = ["S", "ctrl", "shift"]
    focusdown = ["ArrowDown", "shift"]
    up = ["ArrowUp", "ctrl", "shift"]
    select = ["A", "ctrl", "shift"]
    save = ["s", "ctrl"]
    focusup = ["ArrowUp", "shift"]
    down = ["ArrowDown", "ctrl", "shift"]
    new = ["Enter", "ctrl", "shift"]
    paste = ["V", "ctrl", "shift"]
    open = ["O", "ctrl"]
    project-new = ["N", "ctrl", "shift"]

[deps]
Gattino = "f0fb3ee5-f608-41f3-a42d-dac276373afc"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Olive = "724ecaf6-c7a0-4c22-b37e-0bb7b4193da8"
