name = "olive"
uuid = "3aba9d3f-9c1d-4f01-9bdc-e5a7438c0e6b"
authors = ["emmaccode <emmaccode@gmail.com>"]
version = "0.1.0"

[deps]
Olive = "724ecaf6-c7a0-4c22-b37e-0bb7b4193da8"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
SMTPClient = "c35d69d1-b747-5018-a192-25bc5e63c83d"
ToolipsServables = "bf3a9e68-ca66-4981-8178-9d71c4f8abaa"

[olive]
root = "emmac"

[oliveusers.aosj]
group = ["all", "root"]
recents = ["./olive/src/olive.jl"]

    [oliveusers.aosj.creatorkeys]
    "/" = "helprepl"
    ";" = "shellrepl"
    "]" = "pkgrepl"
    c = "code"
    i = "include"
    m = "module"
    v = "markdown"

    [oliveusers.aosj.highlighting.julia]
    abstract = "#006C67"
    begin = "#fc038c"
    char = "#8b0000"
    comment = "#808080"
    default = "#3D3D3D"
    end = "#b81870"
    exit = "#cc0099"
    for = "#fc038c"
    func = "#fc038c"
    funcn = "#2F387B"
    if = "#fc038c"
    import = "#fc038c"
    in = "#006C67"
    interp = "darkred"
    module = "#b81870"
    mutable = "#006C67"
    number = "#8b0000"
    op = "#0C023E"
    string = "#007958"
    struct = "#fc038c"
    type = "#D67229"
    using = "#006C67"

    [oliveusers.aosj.highlighting.markdown]
    bold = "darkblue"
    code = "#8b0000"
    default = "brown"
    heading = "purple"
    italic = "#8b0000"
    keys = "#ffc00"
    link = "#8b0000"
    point = "darkgreen"

    [oliveusers.aosj.highlighting.toml]
    default = "darkblue"
    equals = "purple"
    keys = "#D67229"
    number = "#8b0000"
    string = "#007958"

    [oliveusers.aosj.keybindings]
    copy = ["C", "ctrl", "shift"]
    cut = ["X", "ctrl", "shift"]
    delete = ["Delete", "ctrl", "shift"]
    down = ["ArrowDown", "ctrl", "shift"]
    evaluate = ["Enter", "shift"]
    explorer = ["E", "ctrl"]
    find = ["F", "ctrl"]
    focusdown = ["ArrowDown", "shift"]
    focusup = ["ArrowUp", "shift"]
    new = ["Enter", "ctrl", "shift"]
    open = ["O", "ctrl"]
    paste = ["V", "ctrl", "shift"]
    save = ["s", "ctrl"]
    saveas = ["S", "ctrl", "shift"]
    up = ["ArrowUp", "ctrl", "shift"]

[oliveusers.emmac]
group = ["all", "root"]
recents = ["/home/emmac/dev/packages/olive/OliveCreator.jl/olive/achievements.txt", "/home/emmac/dev/packages/olive/OliveCreator.jl/olive/home/users/emmac/profile/profile.jl", "/home/emmac/dev/packages/olive/OliveCreator.jl/olive/Project.toml", "/home/emmac/dev/packages/olive/OliveCreator.jl/Manifest.toml"]

    [oliveusers.emmac.creatorkeys]
    "/" = "helprepl"
    ";" = "shellrepl"
    "]" = "pkgrepl"
    c = "code"
    i = "include"
    m = "module"
    v = "markdown"

    [oliveusers.emmac.highlighting.julia]
    abstract = "#006C67"
    begin = "#fc038c"
    char = "#8b0000"
    comment = "#808080"
    default = "#3D3D3D"
    end = "#b81870"
    exit = "#cc0099"
    for = "#fc038c"
    func = "#fc038c"
    funcn = "#2F387B"
    if = "#fc038c"
    import = "#fc038c"
    in = "#006C67"
    interp = "darkred"
    module = "#b81870"
    mutable = "#006C67"
    number = "#8b0000"
    op = "#0C023E"
    string = "#007958"
    struct = "#fc038c"
    type = "#D67229"
    using = "#006C67"

    [oliveusers.emmac.highlighting.markdown]
    bold = "darkblue"
    code = "#8b0000"
    default = "brown"
    heading = "purple"
    italic = "#8b0000"
    keys = "#ffc00"
    link = "#8b0000"
    point = "darkgreen"

    [oliveusers.emmac.highlighting.toml]
    default = "darkblue"
    equals = "purple"
    keys = "#D67229"
    number = "#8b0000"
    string = "#007958"

    [oliveusers.emmac.keybindings]
    copy = ["C", "ctrl", "shift"]
    cut = ["X", "ctrl", "shift"]
    delete = ["Delete", "ctrl", "shift"]
    down = ["ArrowDown", "ctrl", "shift"]
    evaluate = ["Enter", "shift"]
    explorer = ["E", "ctrl"]
    find = ["F", "ctrl"]
    focusdown = ["ArrowDown", "shift"]
    focusup = ["ArrowUp", "shift"]
    new = ["Enter", "ctrl", "shift"]
    open = ["O", "ctrl"]
    paste = ["V", "ctrl", "shift"]
    save = ["s", "ctrl"]
    saveas = ["S", "ctrl", "shift"]
    up = ["ArrowUp", "ctrl", "shift"]

[oliveusers.tsit]
group = ["all", "root"]
recents = ["/home/emmac/dev/packages/olive/OliveCreator/Project.toml"]

    [oliveusers.tsit.creatorkeys]
    "/" = "helprepl"
    ";" = "shellrepl"
    "]" = "pkgrepl"
    c = "code"
    i = "include"
    m = "module"
    v = "markdown"

    [oliveusers.tsit.highlighting.julia]
    abstract = "#006C67"
    begin = "#fc038c"
    char = "#8b0000"
    comment = "#808080"
    default = "#3D3D3D"
    end = "#b81870"
    exit = "#cc0099"
    for = "#fc038c"
    func = "#fc038c"
    funcn = "#2F387B"
    if = "#fc038c"
    import = "#fc038c"
    in = "#006C67"
    interp = "darkred"
    module = "#b81870"
    mutable = "#006C67"
    number = "#8b0000"
    op = "#0C023E"
    string = "#007958"
    struct = "#fc038c"
    type = "#D67229"
    using = "#006C67"

    [oliveusers.tsit.highlighting.markdown]
    bold = "darkblue"
    code = "#8b0000"
    default = "brown"
    heading = "purple"
    italic = "#8b0000"
    keys = "#ffc00"
    link = "#8b0000"
    point = "darkgreen"

    [oliveusers.tsit.highlighting.toml]
    default = "darkblue"
    equals = "purple"
    keys = "#D67229"
    number = "#8b0000"
    string = "#007958"

    [oliveusers.tsit.keybindings]
    copy = ["C", "ctrl", "shift"]
    cut = ["X", "ctrl", "shift"]
    delete = ["Delete", "ctrl", "shift"]
    down = ["ArrowDown", "ctrl", "shift"]
    evaluate = ["Enter", "shift"]
    explorer = ["E", "ctrl"]
    find = ["F", "ctrl"]
    focusdown = ["ArrowDown", "shift"]
    focusup = ["ArrowUp", "shift"]
    new = ["Enter", "ctrl", "shift"]
    open = ["O", "ctrl"]
    paste = ["V", "ctrl", "shift"]
    save = ["s", "ctrl"]
    saveas = ["S", "ctrl", "shift"]
    up = ["ArrowUp", "ctrl", "shift"]
